"""
AI Voice Assistant Provider Interface.

Provides a pluggable abstraction layer for voice command processing.
Uses a zero-API-key FreeAIProvider by default, allowing simple addition of
Gemini, OpenAI, or other providers without modifying core application logic.
"""
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session
from app.models.erp import Customer, Supplier, InventoryItem, SalesOrder, PurchaseOrder, Invoice, Task, Project


class BaseAIProvider(ABC):
    """Abstract interface for AI Voice processing providers."""

    @abstractmethod
    def process_command(self, transcript: str, company_id: int, db: Session) -> Dict[str, Any]:
        """
        Process user speech transcript and execute or recommend ERP actions.
        Returns dict with:
            action: str ("navigate", "create", "search", "none")
            target: str (module name or identifier)
            speech: str (text response for TTS synthesis)
            data: optional dict with created or queried details
        """
        pass


class FreeAIProvider(BaseAIProvider):
    """
    Default free AI provider using rule-based NLP & intent matching.
    Does not require end users to provide any API keys.
    """

    def process_command(self, transcript: str, company_id: int, db: Session) -> Dict[str, Any]:
        text = transcript.lower().strip()

        # 1. Navigation / View Intents
        if any(kw in text for kw in ["check inventory", "show inventory", "open inventory", "inventory catalog"]):
            return {"action": "navigate", "target": "inventory", "speech": "Opening your inventory catalog."}
        
        if any(kw in text for kw in ["open crm", "show customer", "list customer", "view customer"]):
            return {"action": "navigate", "target": "customers", "speech": "Opening customer database."}

        if any(kw in text for kw in ["show supplier", "list supplier", "open supplier"]):
            return {"action": "navigate", "target": "suppliers", "speech": "Opening supplier directory."}

        if any(kw in text for kw in ["show sales", "today's sales", "todays sales", "recent sales"]):
            return {"action": "navigate", "target": "sales", "speech": "Displaying sales performance and history."}

        if any(kw in text for kw in ["show invoices", "search invoice", "open invoice", "pending invoice"]):
            return {"action": "navigate", "target": "invoices", "speech": "Opening billing and invoices."}

        if any(kw in text for kw in ["show projects", "open project", "project status"]):
            return {"action": "navigate", "target": "projects", "speech": "Opening project management."}

        if any(kw in text for kw in ["show tasks", "pending tasks", "my tasks"]):
            return {"action": "navigate", "target": "tasks", "speech": "Opening task list."}

        if any(kw in text for kw in ["show attendance", "check attendance", "employee attendance"]):
            return {"action": "navigate", "target": "attendance", "speech": "Opening employee attendance register."}

        if any(kw in text for kw in ["generate payroll", "show payroll", "open payroll"]):
            return {"action": "navigate", "target": "payroll", "speech": "Opening payroll calculation module."}

        if any(kw in text for kw in ["generate reports", "show reports", "analytics", "open reports"]):
            return {"action": "navigate", "target": "reports", "speech": "Opening enterprise reports and analytics."}

        if any(kw in text for kw in ["pending payments", "outstanding payments", "unpaid invoices"]):
            return {"action": "navigate", "target": "invoices", "speech": "Showing pending and unpaid invoices."}

        # 2. Action Intents (Create Records)
        if "add customer" in text or "create customer" in text:
            raw_name = text.replace("add customer", "").replace("create customer", "").strip()
            name = raw_name.title() if raw_name else "New Voice Customer"
            customer = Customer(company_id=company_id, name=name)
            db.add(customer)
            db.commit()
            db.refresh(customer)
            return {
                "action": "refresh",
                "target": "customers",
                "speech": f"Successfully created customer {name}.",
                "data": {"id": customer.id, "name": customer.name}
            }

        if "create task" in text or "add task" in text:
            raw_title = text.replace("create task", "").replace("add task", "").strip()
            title = raw_title.capitalize() if raw_title else "New voice action item"
            task = Task(company_id=company_id, title=title, description="Generated by AI Voice Assistant", priority="medium", status="todo")
            db.add(task)
            db.commit()
            db.refresh(task)
            return {
                "action": "refresh",
                "target": "tasks",
                "speech": f"Created task: {title}.",
                "data": {"id": task.id, "title": task.title}
            }

        if "create invoice" in text:
            import random, string
            inv_num = f"INV-{''.join(random.choices(string.digits, k=6))}"
            inv = Invoice(company_id=company_id, invoice_number=inv_num, total_amount=0.0, status="unpaid")
            db.add(inv)
            db.commit()
            return {
                "action": "refresh",
                "target": "invoices",
                "speech": f"Draft invoice {inv_num} generated.",
                "data": {"invoice_number": inv_num}
            }

        if "create purchase order" in text or "add purchase" in text:
            import random, string
            po_num = f"PO-{''.join(random.choices(string.digits, k=6))}"
            po = PurchaseOrder(company_id=company_id, order_number=po_num, total_amount=0.0, status="pending")
            db.add(po)
            db.commit()
            return {
                "action": "refresh",
                "target": "purchases",
                "speech": f"Purchase Order {po_num} initiated.",
                "data": {"order_number": po_num}
            }

        # 3. Default Conversational Fallback Response
        return {
            "action": "none",
            "target": None,
            "speech": f"I heard: '{transcript}'. You can say: 'show today's sales', 'check inventory', 'create invoice', or 'open reports'."
        }


# Singleton factory instance
_ai_provider: Optional[BaseAIProvider] = None

def get_ai_voice_provider() -> BaseAIProvider:
    global _ai_provider
    if _ai_provider is None:
        _ai_provider = FreeAIProvider()
    return _ai_provider
