"""add erp models

Revision ID: 89c97d3c8262
Revises: e10b1939cf44
Create Date: 2026-07-19 15:32:44.043865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89c97d3c8262'
down_revision: Union[str, None] = 'e10b1939cf44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_company_id'), 'inventory_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_purchase_orders_company_id'), 'purchase_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_sales_orders_company_id'), 'sales_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.add_column('attendance', sa.Column('company_id', sa.Integer(), nullable=False))
    op.drop_index('ix_attendance_date', table_name='attendance')
    op.drop_index('ix_attendance_employee_id', table_name='attendance')
    op.drop_index('ix_attendance_status', table_name='attendance')
    op.create_index(op.f('ix_attendance_company_id'), 'attendance', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_foreign_key(None, 'attendance', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attendance', 'overtime_hours')
    op.drop_column('attendance', 'created_at')
    op.drop_column('attendance', 'work_hours')
    op.drop_column('attendance', 'notes')
    op.add_column('audit_logs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_subject', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('resource', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_table_name', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'record_id')
    op.drop_column('audit_logs', 'table_name')
    op.drop_column('audit_logs', 'user_id')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'new_values')
    op.drop_column('audit_logs', 'old_values')
    op.add_column('customers', sa.Column('address', sa.Text(), nullable=True))
    op.alter_column('customers', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_name', table_name='customers')
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.drop_constraint('customers_company_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'address_line1')
    op.drop_column('customers', 'tax_id')
    op.drop_column('customers', 'contact_person')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'postal_code')
    op.drop_column('customers', 'address_line2')
    op.drop_column('customers', 'customer_type')
    op.drop_column('customers', 'outstanding_balance')
    op.drop_column('customers', 'credit_limit')
    op.alter_column('departments', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('departments_code_key', 'departments', type_='unique')
    op.drop_index('ix_departments_name', table_name='departments')
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.drop_constraint('departments_company_id_fkey', 'departments', type_='foreignkey')
    op.drop_constraint('departments_parent_id_fkey', 'departments', type_='foreignkey')
    op.drop_constraint('departments_head_id_fkey', 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('departments', 'is_active')
    op.drop_column('departments', 'code')
    op.drop_column('departments', 'parent_id')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'head_id')
    op.alter_column('invoices', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_invoices_customer_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_invoice_type', table_name='invoices')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    op.drop_constraint('invoices_company_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_sale_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_created_by_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_purchase_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_vendor_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoices', 'created_by')
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'purchase_id')
    op.drop_column('invoices', 'vendor_id')
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'invoice_date')
    op.drop_column('invoices', 'sale_id')
    op.drop_column('invoices', 'currency')
    op.drop_column('invoices', 'updated_at')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'balance_due')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'terms')
    op.add_column('leave_requests', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('leave_requests', sa.Column('leave_type', sa.String(), nullable=False))
    op.drop_index('ix_leave_requests_employee_id', table_name='leave_requests')
    op.drop_index('ix_leave_requests_status', table_name='leave_requests')
    op.create_index(op.f('ix_leave_requests_company_id'), 'leave_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.drop_constraint('leave_requests_leave_type_id_fkey', 'leave_requests', type_='foreignkey')
    op.drop_constraint('leave_requests_approved_by_fkey', 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('leave_requests', 'total_days')
    op.drop_column('leave_requests', 'approved_by')
    op.drop_column('leave_requests', 'updated_at')
    op.drop_column('leave_requests', 'approved_at')
    op.drop_column('leave_requests', 'leave_type_id')
    op.drop_column('leave_requests', 'rejection_reason')
    op.add_column('notifications', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_notification_type', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'reference_id')
    op.drop_column('notifications', 'user_id')
    op.drop_column('notifications', 'reference_type')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'category')
    op.add_column('payroll', sa.Column('month', sa.String(), nullable=False))
    op.add_column('payroll', sa.Column('allowances', sa.Float(), nullable=True))
    op.add_column('payroll', sa.Column('deductions', sa.Float(), nullable=True))
    op.alter_column('payroll', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payroll', 'basic_salary',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('payroll', 'net_salary',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_payroll_employee_id', table_name='payroll')
    op.drop_index('ix_payroll_status', table_name='payroll')
    op.create_index(op.f('ix_payroll_company_id'), 'payroll', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_id'), 'payroll', ['id'], unique=False)
    op.drop_constraint('payroll_company_id_fkey', 'payroll', type_='foreignkey')
    op.drop_constraint('payroll_created_by_fkey', 'payroll', type_='foreignkey')
    op.create_foreign_key(None, 'payroll', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('payroll', 'gross_salary')
    op.drop_column('payroll', 'other_deductions')
    op.drop_column('payroll', 'created_by')
    op.drop_column('payroll', 'notes')
    op.drop_column('payroll', 'payment_method')
    op.drop_column('payroll', 'hra')
    op.drop_column('payroll', 'bonus')
    op.drop_column('payroll', 'pay_period_start')
    op.drop_column('payroll', 'tax_deduction')
    op.drop_column('payroll', 'other_allowances')
    op.drop_column('payroll', 'updated_at')
    op.drop_column('payroll', 'pay_period_end')
    op.drop_column('payroll', 'payment_date')
    op.drop_column('payroll', 'overtime_pay')
    op.drop_column('payroll', 'da')
    op.drop_column('payroll', 'overtime_hours')
    op.drop_column('payroll', 'pf_deduction')
    op.drop_column('payroll', 'total_deductions')
    op.alter_column('projects', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'budget',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_constraint('projects_code_key', 'projects', type_='unique')
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint('projects_manager_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_customer_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_company_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'spent')
    op.drop_column('projects', 'code')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'deadline')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'manager_id')
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('spent', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_company_id_fkey', 'projects', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('projects_customer_id_fkey', 'projects', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('projects_manager_id_fkey', 'projects', 'users', ['manager_id'], ['id'])
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.create_unique_constraint('projects_code_key', 'projects', ['code'])
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.alter_column('projects', 'budget',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('projects', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('payroll', sa.Column('total_deductions', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('pf_deduction', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('overtime_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('da', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('overtime_pay', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('pay_period_end', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('payroll', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('other_allowances', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('tax_deduction', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('pay_period_start', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('payroll', sa.Column('bonus', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('hra', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('other_deductions', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('payroll', sa.Column('gross_salary', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payroll', type_='foreignkey')
    op.create_foreign_key('payroll_created_by_fkey', 'payroll', 'users', ['created_by'], ['id'])
    op.create_foreign_key('payroll_company_id_fkey', 'payroll', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_payroll_id'), table_name='payroll')
    op.drop_index(op.f('ix_payroll_company_id'), table_name='payroll')
    op.create_index('ix_payroll_status', 'payroll', ['status'], unique=False)
    op.create_index('ix_payroll_employee_id', 'payroll', ['employee_id'], unique=False)
    op.alter_column('payroll', 'net_salary',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('payroll', 'basic_salary',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('payroll', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payroll', 'deductions')
    op.drop_column('payroll', 'allowances')
    op.drop_column('payroll', 'month')
    op.add_column('notifications', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.drop_column('notifications', 'employee_id')
    op.drop_column('notifications', 'company_id')
    op.add_column('leave_requests', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('leave_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('leave_requests', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('total_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key('leave_requests_approved_by_fkey', 'leave_requests', 'users', ['approved_by'], ['id'])
    op.create_foreign_key('leave_requests_leave_type_id_fkey', 'leave_requests', 'leave_types', ['leave_type_id'], ['id'])
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_company_id'), table_name='leave_requests')
    op.create_index('ix_leave_requests_status', 'leave_requests', ['status'], unique=False)
    op.create_index('ix_leave_requests_employee_id', 'leave_requests', ['employee_id'], unique=False)
    op.drop_column('leave_requests', 'leave_type')
    op.drop_column('leave_requests', 'company_id')
    op.add_column('invoices', sa.Column('terms', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('balance_due', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('tax_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('invoice_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('discount_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_vendor_id_fkey', 'invoices', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key('invoices_purchase_id_fkey', 'invoices', 'purchases', ['purchase_id'], ['id'])
    op.create_foreign_key('invoices_created_by_fkey', 'invoices', 'users', ['created_by'], ['id'])
    op.create_foreign_key('invoices_sale_id_fkey', 'invoices', 'sales', ['sale_id'], ['id'])
    op.create_foreign_key('invoices_company_id_fkey', 'invoices', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_invoice_type', 'invoices', ['invoice_type'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_customer_id', 'invoices', ['customer_id'], unique=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('departments', sa.Column('head_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('departments', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key('departments_head_id_fkey', 'departments', 'employees', ['head_id'], ['id'])
    op.create_foreign_key('departments_parent_id_fkey', 'departments', 'departments', ['parent_id'], ['id'])
    op.create_foreign_key('departments_company_id_fkey', 'departments', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.create_index('ix_departments_name', 'departments', ['name'], unique=False)
    op.create_unique_constraint('departments_code_key', 'departments', ['code'])
    op.alter_column('departments', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('customers', sa.Column('credit_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('outstanding_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('customer_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_company_id_fkey', 'customers', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customers', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('customers', 'address')
    op.add_column('audit_logs', sa.Column('old_values', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('new_values', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_table_name', 'audit_logs', ['table_name'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'resource')
    op.drop_column('audit_logs', 'user_subject')
    op.drop_column('audit_logs', 'company_id')
    op.add_column('attendance', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('work_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('overtime_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_company_id'), table_name='attendance')
    op.create_index('ix_attendance_status', 'attendance', ['status'], unique=False)
    op.create_index('ix_attendance_employee_id', 'attendance', ['employee_id'], unique=False)
    op.create_index('ix_attendance_date', 'attendance', ['date'], unique=False)
    op.drop_column('attendance', 'company_id')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_company_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_company_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_company_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
