"""Initial models

Revision ID: e10b1939cf44
Revises: 
Create Date: 2026-07-19 12:16:02.474674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e10b1939cf44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_requests_email'), 'otp_requests', ['email'], unique=False)
    op.create_index(op.f('ix_otp_requests_id'), 'otp_requests', ['id'], unique=False)
    op.add_column('companies', sa.Column('company_name', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('company_type', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('owner_name', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('business_email', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('mobile_number', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('password', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('company_code', sa.String(), nullable=False))
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_companies_name', table_name='companies')
    op.create_index(op.f('ix_companies_business_email'), 'companies', ['business_email'], unique=True)
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.drop_column('companies', 'tax_id')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'currency')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'name')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'address_line2')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'legal_name')
    op.drop_column('companies', 'address_line1')
    op.add_column('employees', sa.Column('employee_name', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('employee_email', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('mobile_number', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('department', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('password', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('role', sa.String(), nullable=True))
    op.alter_column('employees', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_employees_department_id', table_name='employees')
    op.drop_index('ix_employees_email', table_name='employees')
    op.drop_index('ix_employees_employee_id', table_name='employees')
    op.drop_index('ix_employees_status', table_name='employees')
    op.drop_index('ix_employees_user_id', table_name='employees')
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_email'), 'employees', ['employee_email'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.drop_constraint('employees_user_id_fkey', 'employees', type_='foreignkey')
    op.drop_constraint('employees_department_id_fkey', 'employees', type_='foreignkey')
    op.drop_constraint('employees_company_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('employees', 'bank_ifsc')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'department_id')
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'bank_account')
    op.drop_column('employees', 'state')
    op.drop_column('employees', 'pan_number')
    op.drop_column('employees', 'emergency_contact_name')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'notes')
    op.drop_column('employees', 'employee_id')
    op.drop_column('employees', 'emergency_contact_phone')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'date_of_birth')
    op.drop_column('employees', 'bank_name')
    op.drop_column('employees', 'salary')
    op.drop_column('employees', 'end_date')
    op.drop_column('employees', 'user_id')
    op.drop_column('employees', 'city')
    op.drop_column('employees', 'country')
    op.drop_column('employees', 'aadhar_number')
    op.drop_column('employees', 'employment_type')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'postal_code')
    op.drop_column('employees', 'join_date')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('join_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('employment_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('aadhar_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('salary', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('bank_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('employee_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('emergency_contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('pan_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('bank_account', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('bank_ifsc', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_company_id_fkey', 'employees', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('employees_department_id_fkey', 'employees', 'departments', ['department_id'], ['id'])
    op.create_foreign_key('employees_user_id_fkey', 'employees', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.create_index('ix_employees_user_id', 'employees', ['user_id'], unique=False)
    op.create_index('ix_employees_status', 'employees', ['status'], unique=False)
    op.create_index('ix_employees_employee_id', 'employees', ['employee_id'], unique=True)
    op.create_index('ix_employees_email', 'employees', ['email'], unique=False)
    op.create_index('ix_employees_department_id', 'employees', ['department_id'], unique=False)
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'is_active')
    op.drop_column('employees', 'password')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'mobile_number')
    op.drop_column('employees', 'employee_email')
    op.drop_column('employees', 'employee_name')
    op.add_column('companies', sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_business_email'), table_name='companies')
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False)
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('companies', 'company_code')
    op.drop_column('companies', 'password')
    op.drop_column('companies', 'mobile_number')
    op.drop_column('companies', 'business_email')
    op.drop_column('companies', 'owner_name')
    op.drop_column('companies', 'company_type')
    op.drop_column('companies', 'company_name')
    op.drop_index(op.f('ix_otp_requests_id'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_email'), table_name='otp_requests')
    op.drop_table('otp_requests')
    # ### end Alembic commands ###
